language: node_js

git:
  depth: 1

node_js:
  - '12'

before_install:
  - rm -r node_modules
  - nvm install-latest-npm

install:
  - npx install-peerdeps --dev eslint-config-airbnb
  - npm install ms
  - npm install 

script:
  - npm run lint
 